options(max.print=100000000)


contaPalavras <- function(linhas) {
  palavras <- strsplit(linhas, "\\W+")
  todas <- unlist(palavras)
  contagem <- table(todas)
  contagem[order(-contagem)]
}
linhas <- c("O bonde tá não ver é isso, né o galo canta e diz assim desperta desperta que eu tô aqui já tem já tem dois anos na panela, já tem dois Coitada já cozinhando já sabe demais é o seguinte, nós vamos para o momento da nossa conversa a conversa que a gente quer realmente ter com vocês voltado para responder no momento, né? O projeto já imprimir se chama raízes da resiliência, então como é raízes o chame ela meu filho que a oportunidade chegou o Marcelo também ele ele é daqui também estava dentro também do pode colocar também ainda tem até 12, eu acho que


Foi com ele fechou o jogo e o garoto aqui ó e nós temos estamos estamos tendo duas reuniões, entendeu? Então mantendo essa daqui é o senhor vai participar daquela lá é viu? Que chama sua esposa para ela uma amizade que explica o senhor. Obrigado Marcelo. Vamos adiantar aqui que a gente viu, viu lá tem isso aí nós gostaríamos de ouvir de vocês um pouco sobre a diversidade das expressões da cultura do lugar da cultura que vocês vivem, né? Especificamente voltado para alguns pontos danças literatura Campos artesanato grafismo. Tem alguém aqui que trabalha com grafismo também não é? É mas especificamente voltado para três aspectos.


Essa diversidade de expressões da cultura os saberes locais o que tem uma relação com essa diversidade, mas cada uma dessas categorias, a gente tá dando um alguns pontos para ser discutir e é espiritualidade, tá? Então vou voltar é espiritualidade os cabelos locais e diversas outras expressões de Aventura tá? Então a gente vai meio que deixar vocês à vontade para falarem, por exemplo sobre as danças existentes aqui ou que existiram o que ouviram seus pais falar que seus pais diziam né as danças o que existe de literatura cantos cantos de antes de hoje presentes ainda hoje artesanatos grafismo indígena, aí vocês falam tá bem?


Aqui professora tem tem é muito forte eh a cultura por ser mistificado assim de ter a história dos Quilombolas aqui, né? Que trouxe o coco aqui o pessoal da colônia dos pescadores antigos que moravam na vida do mar. Eles faziam uma Ciranda e se deslocavam daqui quero pessoal quero indígena também deslocava daqui para para fazer no Ipiranga um pouco e eles também vinha para beira da praia e também a história do do dos Tabajaras também que entra na na mesma história também dos pescadores que surge nativos daqui mesmo e depois foi como José ele.


Tem que a história quando foi afastado foi perseguido, esse povo correu todo para aqui para para você ficar bom que alguns ficaram e tiveram que se submeter a trabalhar para esses coronel's que chegaram aqui e essa família que veio de de fora e é por aí essas três três evidência de Cultura aqui é o coco a ciranda e uma torém que mais poderiamos falar sobre sobre complementando a fala dele, né? Ele ele surgira é os navios Negreiro se ia entrar Porto de Galinhas que vinha de África.


E vamos para Porto de Galinhas e alguns Náufragos, né? Desaguaram aqui em Carapibus e pediram licença para passar e os indígenas Tabajaras autorizaram e eles foram construídos de Ipiranga e corujinha de açúcar, mas alguém gostaria também de falar complementar acrescentar o reforçar tem experiência aqui sobre sobre pescaria sobre dança.


Então tudo criado com meu pai aqui na pesca, né? Fica com meu pai foi foi pescar e aceitar assim com tecido. Qual é a próxima é muito difícil, mas era bom a gente era mais feliz hoje no dia violência, né? E muita coisa aconteceu meu Deus do desenvolvimento, mas tem muita muita história assim, eu não sentia mais quando eu era brasileiro naquela época que tinha uns caminhãozinho de formiga que a gente chamava para menina também assim também é muito de troca naquela época, meu pai tinha uns parentes aqui que era preciso ficar boa.


Eles vinham trocar a manga a gente trocava ele levava a manga e a gente meu pai tava de peixe para não soltar a gente esperava ele né? Assim no dia que ele vinha e eu não tinha nem inteirinho com um samurai assim na cabeça e ele deixava assim a as manga e a gente já colocava lá peixe, ele pegava de novo e voltava, mas não beleza, mas com vocês que linda deu uma lembrança muito boa assim ainda hoje essa troca existe ou não não pode não existir mais essa essa troca porque foi abaixado a uma vida um filho um casamento e se misturando as coisas tão engraçado de novo, né um pouco da história porque assim a gente viveu lá, a gente não vai me dizer agora.


Religião assim Dona Gorete alguma religião alguma dança a gente vai chegar naquele momento da espiritualidade, mas por exemplo a Gorete não só agora mas o cacique também os demais é os seus pais falavam da aqui teve relatos, né da dança de coco da Ciranda, né? Da do e do Dr. É foram as três danças citadas aqui, vocês teria alguma coisa mais a colocar de experiência vivenciadas ou pelo menos que seus pais e seus avós falavam ouvir. Hoje existe alguma coisa ainda acontecendo sobre as danças e por baixo eu sou bastante gente eu tenho uma lembrança muito feliz que eu pego o dia, né? Porque foi ele foi um fundador do Povo, né? Hoje tem que estar sem sem sem sem sem sem sem Ana do guri, mas não foi ela foi quem?


Amanhã cedo né um pouco pois seu Zé pontinha ele ele era uma senhora era uma senhora já faleceu homem enganando aí, mas ele quem apresentava aí fazia aquela infância um pouco aí quando dava meia-noite uma hora da manhã, aí eles iam tudo para o rio que chamava o rio guru lá nesse Rio aí minha mãe contava muito também. Aí ficava as mulheres dizia logo as mulheres ficava assim e quando dava aquela certa hora aí as mulher ia se banhar, viu? Aí depois os números era quem quando as mulheres subia e os homens os homens que ia né assim depois desse corpo e depois Era só a batida dele cachaça e tudo mais era festa que começa a época a gente então um tema muito pouco e hoje não existe mais.


Existe assim no Ipiranga, mas não dessa forma né com outra pessoa com a filha de de uma das Coqueiros na época que era eh lemira, né? Era duas irmãs também com com com uma tia avó da gente que é 13, análise, vamos vamos vamos vamos vamos vamos né, Rosana? Rosa, ela fazia bonequinha de pano hoje a gente não ver mais né bonequinha de pano vermelho os brinquedos da gente era esse e ela fazia e dava para vir aqui comprar a Dona Rosa tudo dançando coco lá com esse pessoal aqui, eu não lembro disso.


Duas onças soltas na carreira pro lado daí eu fui lá eu disse Sai do Meio Marcelo era pequeno, mas já tinha essa barba branca branca aqui tinha uma pescaria que era tradicional aqui do pessoal que vivia na na vida dos pescadores que era na vida da praia se chamava Currais de peixe e hoje não existe mais aqui, né? Existe em algumas praias muito raras que é uma uma seguindo assim, ó, quem sabe explicar melhor Marcelo. Aí meu Deus perseguição do Ibama, né? Faltava muito com madeira do mato mesmo cadeira Redonda, eu quero fazer esses pontos de madeira.


Errada aquelas madeiras de Serraria que se tornou arrancada, entendeu? É a maioria do pessoal que que tem os corrói, não quero mais conferir porque torna caro e tô desistindo esse óculos escuras tão sai acabando, né, mas não tem nada a ver o Curral com as camboas escambo não porque é a maré, né? E esse Curral são uma Maré que eu falo assim são horrível, né na beira do do mar vai entrando e faz um um coração assim, tipo um coração que o peixe entra e facilita eh oh pescador não ir para o alto mar e tal. Aí ficava assim o cara mais fácil para o pescador nativo que tinha uma jangadinha feito de de pedaço de pau, né, mano para não ir para o alto mar para passar naquele tempo não tinha botado. Não mesmo, parece que você quis dizer aqui aqui é todo mundo falando.


E artesanato como é que vocês vêm essa questão dos artefatos aqui vocês trabalham com madeira e pedra aqui, o pessoal faz isso também, né? A panela de barro, sei lá, porque até as vassouras é feita de de de de de de de comprava vassoura é feito do mato mesmo, né? Apesar frontal e mato, ele é um negócio bem primitivo mesmo. Quem quem vivia assim. Os relatos que eu vi o vídeo das pessoas mais velhas. Era que realmente eles viviam assim na época primitiva mesmo era casado de palha e a pescaria com Jangada simples com vela, ela disse que tinha vela era mais chique, né?

Pra pra ir pescar mais longe e os outros brincavam por ali mesmo e tinha a questão do do das Caiçaras mesmo. Parece Caiçaras da do pro rabo de peixe que era onde o peixe ficavam dava muito xaréu nessa época antigamente tinha muito xaréu e outros peixes, né? Que quando ele entra ele o peixe fica na sombra, ele não tenha saído, mas ele não consegue mais sair, entendeu? Recordar aí dos Curral, né? Que era escovar né? Aí um Mike aqui, pede para ela receber todas. Pede para ela ficar recebendo aí as pessoas por favor.


Qual eu acho que era Amanda, viu? Isso é torta eu nem recordo mais é tanta antena isso aí meu bem. Isso aqui é a moça bisavó a nossa bisavó, Praia do amor.


Você não precisa não, meu amor. Ali olha, Carapebus, você é uma pessoa maravilhosa Iracema, né? Agora as fotos tá encantando todas as mulheres, eu pergunto a você não se não você não se apoie que a gente fotografa de material Tranquilo isso aqui ela levantando, né levantando essas estrelas que sentado vamos prender, beleza? Eu gostaria de a gente continuar e ele


Que a falta e depois o sorvete para poder tem dias que vai querer desocupar mais rápido possível para ir para lá para outra reunião hoje, muito material É uma relíquia maravilhosa. É só o povo diz que já tá baseada na Paraíba, viu? Que delícia e dai. Que coisa linda que eu não tô conseguindo muito obrigada sobre o grafismo. Alguém disse aqui que era trabalha com grafismo, não é também né, Lucas, né? Falou alguma coisa vocês aí sobre o grafite, né? Umas palavras.


Tem algumas fotos aí que foram dessa outra que a gente construiu tá entendendo? Aí também acerte elas aí se vocês quiserem tocar no assunto, depois a gente conversa a respeito dela também perfeito dos dois tigre e já apareceram aí quando eu vi que ele disse que ele já tava com uma barba branca de guerra. Isso é imaginar o computador, então nós temos artesãos aqui nós temos duas balas, viu, Juscelino tem a fala mostrando que eles fazem para vender.


É muito bonito. Olha só eu vi sobre o grafismo. Vamos ouvir sobre o grafismo é feito com frutas e com sementes que é Urucum o jenipapo ele fica tinta preta e tem vários significados dependendo do simbolismo do grafismo agora e me perdoem cada uma tem uma cidade dependendo da apresentação Lucas.


Não opa Urucum, qualquer coisa mais linda gente esse homem da guia do mar de fora e do lado de dentro do marido dessa história de fora do Wagner tudo. Ele disse isso bateu, viu? Ainda agricultura de fora de dentro ele ele é negando a menina dele que diz que é o que é o Maraca Maracanã, ela comeu ela fica Maracanã, ele podia dar uma seca ela que já tá balançando, né? Aí ele dá medo é porque ele seco é que tem um espelho seca esses Picos não seca e tinha um espinho machuca o dedo dela esse urubu professora, ele tanto pinta com ele assim natural. Como pode fazer o doce para ele ficar uma uma uma pasta e o jenipapo? Ele é mais machucado, né? Mas triturado aí o caldo se torna uma tinta preta, tá? Você tava falando eu sou um simbolismo, nunca poderia falar alguma coisa nesse


Tem simbolismo do olho do Jacaré tem simbolismo da Maré da Jibóia das raízes da Colmeia entre outros e tudo isso desenhado no corpo a pintura tá na cabeça e o que você gosta mais de fazer a pintura que eu mais gosto de fazer uma pintura ancestral que é mais antiga do nosso povo que a maioria das jiboia da Jiboia que quer dizer, o que significa proteção todo tipo de serpente significa proteção para o nosso público todo tipo de serpente significa proteção para o nosso povo muito interessante trabalhando com os Matos. Se lá no norte, né? Eles colocam eles dizem que são filhos de uma grande serpente que vive no Lago dentro da terra. Olha que coisa bonita, né? E eles são protegidos por essa grande mas lá.


Paco sim, né, olha como há uma briga uma por Helena, né interessante, vamos ficar aqui tá vazado é Tabajara eh sobre os cantos alguém lembra algum canto antigo além do Toré e o Toré. O que significa para vocês? O Toré é muito bom Sagrado do nosso povo, conhecimento e sabedoria através da dança através da da música e é uma festividade, né? É uma realização espiritual, pode significar também outra coisa, tipo momento de luta é um grito de guerra também.


Falando né? É É um contato com a natureza e a gente na Pisada e essa ligação se ela que que nos une e a gente sente as batidas dentro da gente o toreo chamado do povo que quando a gente chegou em Botucatu é bem pouquinho a gente né? E a gente começou ali com cinco pessoas dançando Toré e começou a juntar a gente juntar a gente junto a gente e hoje Quatro também né? É uma chama do jeito é aqui a gente tem que tá aqui eh como eh, Jasmim também falando batendo que a gente tá aqui. A gente ficou escutando a zoada porque a gente tá aqui empurra o vinho. Aí eu cheguei até tímido, né? Como muita gente cinco pessoas no Toré eu via no no nos vídeos aí e hoje tá aqui essa multidão de gente e ele vai aumentar mais ainda cada vez isso aí é o Toré chamando o que dizer que o da Baixada tá aqui, ele tá resistente e que a terra de volta eu acho que o torneio para mim é isso.


Que ele falou ali todo mundo bem É sobre a medicina indígena que vocês teriam a falar.

Sobre a medicina indígena aí entra chás entra às vezes a as as rezadeiras dos vendedores vendedoras parceiras, né? Símbolos de proteção que vocês possam usar o show do abacate, ele serve para muita coisa, né? Você pega três folhas é cozinha para 3 litros de água serve para infecção urinária para dor no estômago tá peso, né para diabético para tomar um pouco e também tem o jenipapo, né que a gente faz lambedor para todo tipo de enfermidade dos próximos, eu também tenho a Pitanga, né? O olho da Pitanga quando está com a disenteria diarreia, né? A gente mastiga ou a gente faz o chá para parar a disenteria também. Tem um chá que se chama é uma folha que se chama para tudo e


Pessoas conhecem como boldo o boldo do chile, né? E também serve para isso também para dor no corpo e dor de barriga e vocês costumam usar os chás, eh e a Amora para a saúde da mulher, né também para diminuir quando tá nos tempo demais, né? Você vai tomando vai controlando você pega a folha maior parte no meio vai para 3 litros de água. Fica tomando e também para peso para muita coisa e também a cansou, né? Que hoje a gente quase não vê mais ele é um ele dá dentro da pedra de uma pedra, sai de dentro das Pedras onde tem aquelas pedras aqui Seco, não sei aí sai ele tem umas folhinha o meu pai, tirava a raiz e levava para fazer chá para nós, né? E também como que é fazer também o a salsa da praia.


Muita gente pergunta assim eu fui na praia e peguei essa alça porque tava com coceira. Mas aquela salsa que apanha aquelas que tem as Flores Roxa, não é aquela salsa a salsa mesmo a legítima ela ela tá debaixo da Areia ela ela enrama ela bota umas folhinhas verdinha miudinha umas florzinha Branca, eu vou secar vontade puxando a Raíssa a Raíssa ela ela ela ela é bem branquinha bem branquinha a raiz dela. E aí quase muchacha em casa assim começa com febre alguma irritação no corpo não tem tempo tinha o sarampo, né? Essas coisas assim aí usava muito esse esse esse chá que era da da salsinha da Aliás, hoje em dia muita gente não conhece ele não conhece a raiz do do guajuru é bom para diabetes mesmo também usado para o Diabetes, sim e Gorete. Você tem visto ainda essa raiz de guajuru quase não existe sim.


Mas ele não quando você chegar ali na beira da praia você encontra né? Todo mundo aqui conhece um Guajiru e eu alimento tá anotando seu livro. A fruta responde eu aprendi a fazer com o meu meu pai minha mãe, né? Porque Naquele tempo era tão difícil as coisas, a gente tava muito era de bater botar para fazer assar o peixe a gente comia até com farinha na época tudo muito difícil e é a gente sabe galera, a gente comia eles com farinha, ele é muito gostoso. Ele fazia batia no frio não agora tem um processo muito grande porque é trabalhoso, porque ele a gente tem que escolher o mundo esses meses que dá né?


Então a gente olha Deus te abençoe, meu amor. Aí a gente pega o surto e tem um processo todo até quando a maré tá enchendo e quando o maré tá secando que desiste, ele disse que aumentava mais né? Aí a minha mãe fazia era para quando não vai chegar naquele tempo situação meio aí a gente usava o óleo de bate por trás ou o óleo do Coco isso aí eu ainda tenho uma memória boa que e ainda uso hoje o óleo de réplica tá hoje a gente quase não uso porque ele não trabalhou tudo trabalhando de saber né? A gente que até a Ana do povo lá no fundo dela, tá tendo um processo tá fazendo mas eu sei fazer mas eu não ele tem escasso também, né? É descanso, mas nessa época.


Mas se tivesse uma oficina para você ensinar os Tabajara a produzir o óleo de bate e botar como uma medicina você faria que tiver Faria sim, pelo menos ficava ali mostrando como era que tu fazia isso aqui na frente de casa. Tem um pé, né? Porque a vontade de Deus eu deixei ele lá para derreter reproduzir eu tá grandão agora ai ai ai é isso que a gente a gente ficou lá atrás a gente passar né? Porque eu não vi a gente vai né? A passagem da gente vai passar aqui e a gente vai seguir, né? E vai ficar o último conhecimento, né? Já não lembro muito sabe? Como é que se faz, mas é um processo muito parecido. Alguém conhece sobre o óleo do Dendê. Aqui eu conheço um colocado da minha mãe passou para mim, né? Que tinha que colher com uma pena para


No caso ele jogava nada para cima e colhia com a pena, mas eu não fiz não é ficar só olhando ela ver ela ela fazia que liga pelo menos faz Fazia era uma mistura da gente quando não tinha carne aí mãe, botava um pratinho faz o bolo de feijão e a gente comia óleo de dendê como se fosse a mistura gostoso mesmo, né? Ele é muito gostoso fazer eu faço se tiver uma oficina para você ensinar você ensina né? Imagina Juscelino tá aí a gente fazendo. Esse estudo não tem potencial para vários, por exemplo buscar um recurso no edital para pagar os mestres das Aldeias, né? Coisa bonita, imagina vocês, além de ensinar dentro de um projeto que a gente possa captar um recurso sem receber um dinheirinho também, né? Melhor do que o dinheiro não é isso? É melhor é o os as nossas crianças aprender para passar futuramente o capital grandioso. Olha só para dizer olha enquanto você não tá lá perto aqui. Pega aí ó e diferença não fica aqui ó, cuida da minha mãe, né?


É coisinha e experiência que eu eu eu eu tive dela e eu posso passar essa é a visão maravilhosa aqui que a gente precisa ter não é eu estou tirando o abacate também serve assim, não sei como uma comida ele fez mal você pode tomar ele você vomita que você não tem e serve para quem gosta de beber também quando ofende com a barriga inchada quando ele mata ele seu resolve é um antitóxico, né? Agora só no tampa de casa, né? A pessoa não pode tomar em grande quantidade e assim quando tomar é melhor ficar em casa, porque a gente vai fazer porque ali é coisa muito, né? Ei tu fala do chá do do lambedor do Cupim fazendo cupim. Eu também fazer que o BTS é o tacho para fazer vai passar da minha mãe assim as pessoas antigas falam que


De cupim a pessoa que tem cansaço, você dá essa pessoa, só que você não pode falar de que é o lambedor que é para fazer o efeito, né? É o cupim e o esterco de Passarinho, né? Ela tinha alcançasse é zero trouxe para a mãe ia fazer 6 ela tomou e ela ficou boa, né? Primeiramente Deus segundo o lambedor que ela tomou né? Sim, sim tem rapadura quando tapete o cavalo marinho aquele que pescando aí botei ele para secar me lembro que minha mãe falou que tava ali no chão, só não pode saber, né? As pessoas faz parte da cura o segredo né aí entendeu? Tá bem, graças a Deus também muito bem. Se fosse uma outra repeti ensinando aos mais jovens que vocês fariam isso.

Muito bem, vou buscar ela mata minha faca em cima a ele, eu sei onde ele ir buscar na máquina onde minha sobrinha chegou aqui e disse ao pé de cana não isso é Bambu tá entendendo? Porque se mandioca não conhece as coisas aí tem que levar ele para é de dizer onde eu ver como é que tira o Dendê, como é que corta o DDD porque dentro do balde mágica para você tudo é diferente. Tem que passar para ele. Hum, meu dedo tem uma umas espinhos, aí vocês podem cortar de todo jeito não aí ele machucar você, né? Depois a gente passar para talvez quem sabe realizar a oficinas intercambiando o conhecimento, né da de uma aldeia com a outra eu vejo um diálogo muito parecido tá? Tem muitas informações que mais vocês tem uma sobre valorização dos sinais da natureza e também sobre a o símbolo de proteção da natureza como como é que vocês ganham essa questão Protetora da na


Tem algumas experiências que vocês podem citar a destruição, né do ser humano, né? Porque a natureza é tudo para nós, né? A gente só se inspira você respirar também, né? Cheguei aí que essa essa mochila aí do Rio Grande do Sul, eles acusa muito porque ele construiu muito e e construir eu penso que tem uma área lá que quando foi aterrada assim que a água Vinha ela ficava dentro da do das plantas são lá, né? E ela não invadiu tanto para a cidade porque a gente tem que proteger porque a gente não sabe do amanhã, né? Aí como aqui a mata aqui que eles queriam destruir. Nossa mata aqui sozinha antes, ele pediu cortar tudo ali ali tem pé de ação sua. Nossa munduba e tudo bem.


Se tiver assim que a gente tem que ter sempre na alerta e o ruído é muito bom, porque ele é um protetor da natureza, ele não destrói porque na verdade como se fala assim os homens brancos, né? Homem branco que fala que são os grandes Empreendimentos cada cidade nós vemos aí que o que as autoridades como Prefeito governadores vereadores, né esse tipo de pessoas aí eles estão envolvido muito com construção, eles estão envolvidos muito com construções e a tendência a tendência dos homens é crescer não vamos crescer o conde seu Conde então, eles têm que crescer o fundo e aonde então eles querem crescer o conde destruindo as nossas matas tanto que nós protegemos aqui a mata aqui.


E eles querem destruir. E aí dois homens aí de dinheiro, eles dizem que tem 250 hectares de terra para construir um risoto, já que tocou em proteção aí não vou citar isso aí porque existe aí uma rede aí de de de de de de de de de de hotel, né? Vocês estão querendo fazer uma grande Resort aqui aqui no conde aqui é atentaram derrubar as matas ali com o motor Serra nós ia Nós aprendemos os motosserras caçambas e entregando material para eles dessa vez agora. Acho que tá o que uns 8 meses ou mais um ano fez um ano isso aí não né? Primeiro de Janeiro, né? Faz um ano. Mas a outra foi só sete meses quatro meses. Então tem o quê? Dois tratores dentro nós pedimos lá, né? Aprendemos.


Eh veio Prefeitura de Conde juntamente com com guarda municipal veio assessora da prefeita nos pedindo para entregar a chave do do do do da máquina porque protege a natureza que é a sudema que protege então houve esse moído tudo aí então saiu dizem que é um rapaz aí que trabalha para um tal de de teste e e Fernando então esses dois homens aí andaram procurando os Cacique para fazer um acordo certo oferecendo 30 mil reais mais ou menos para cada Cacique um carro 50 50 parcela de de de de r$ 3000 por mês e uma mini Granja para cada Cacique para assinar, entendeu? Inclusive um veio diretamente falando para fazer a cor do disso. Aí eu disse Fernando que o Fernando eu não trabalhei para o senhor.


Para fazer acordo com o senhor certo e outra coisa eu prefiro deixar a a luta e sair de cabeça erguida do que trair meu povo eu vou colocar uma mixaria no meu bolso certo traiu o povo que me deu tanta confiança e levantou como Cacique para eu ter o que um carro eu queria uma mixaria que se acaba, entendeu? Enquanto isso vou perder a confiança. Me desculpa a expressão. Vamos abrir as pernas para todos os Empreendimentos que quiserem vir fazer aqui no no litoral sul aqui vai falar vai vir fazer nós vamos perder a confiança do Ministério Público Funai e diz outro e diz outros órgãos que estão nos apoiando certo aí se vendendo, entendeu? Então isso é feio é tu é ruim, então o que eu falo de proteção É isso aí e os homens Branco, eles querem eu vou fazer de tudo para tentar derrubar as nossas matas e construir isso é coisa que nós nós.


Indígena que estamos aí eh protegendo na verdade. Eh eh as matas os rios porque as fábricas também no momento que que faz o que uma fábrica que aqui no território exemplo que nem Elizabeth, eles dizia assim não vai surgir muito emprego para família de vocês realmente mas nós indígenas vai ser sujeito a estar trabalhando para eles e ele jogando naquela cauda entendesse é tirando os minérios da terra a proteção da terra que é essa camada de cima que serve de adubo para tá extraindo ali minério que nem pedra daqui a um ano dois anos cinco anos 10 anos para frente aquela Terra ali, não presta para nada todo todos os mulecada, entendeu? E cadê os índios que era para estar protegendo certo, então é isso que eu digo aos meus parentes como das mãos proteger vamos para a luta. Vamos em frente para proteger para que?


Venha é esse desmatamento para o nosso território e que não venha eh poluição nos rios nas praias que nem tem muitos tem muitos aí Hotel aí né? Aí jogando esgoto esgoto para dentro, entendeu? Então É isso aí gente certo, a gente tem um grande exemplo. A gente tem os bares na praia por um nativo, né? O pessoal aqui da área mesmo querem indígena também uma parte indígena, a gente é 30 e 6 bares na praia foram tirando tudo. E hoje esse pessoal tá tudo escravizado dentro de pousada galera 40 reais por dia quando eles podia realmente ter o seu próprio emprego. Pensa no meu time e a gente tem que ficar mais atento ainda porque estão os Senador fez um barco é o pack de de privatizar as praias junto com o jogador com um jogador de futebol que o Neymar e eles tão querendo privatizar.


Saia a gente tem que ficar muito atento esse esse momento que a gente tá passando cobrar dos políticos daqui para votar contra e os que votarem a favor a gente botar o nome deles e fazer alguma até reivindicação maior com isso com os indígenas. Se esse negócio realmente passar né? Tudo que vocês estão falando é verdade? Gostaria de falar mais sobre essa questão a gente a gente quando os pais já ficaram Certa idade e a gente continua tudo na beira de praia trabalhando, eu trabalhei 40 anos na beira de praia na beira de praia, aliás, depois veio essa aí vai virar tudo então só besteira na praia nos barracos barbudo, deixa ele trabalhar, mas minhas pousadas nesses cantos.


A minha família era toda sobrevivência.


É feito ele tá falando, né? Que a Gorete tá emocionada pelo que ela tá falando tá gente? É verdade emociona assim porque a gente vê a gente foi muito maltratado, entendeu? Mas no mesmo tempo eu tenho muito orgulho me casei construir uma família hoje tua filha formada, entendeu? Não foi brincadeira foi mudando queimando o bolo crente, mas consegui eu meu filho também que não quis continuar os estudos, mas mas senhor a vizinha dele hoje aprender a me aposentei e um cantinho que eu trabalhava que eu abri os braços. Quando eles vieram para mim engolir, eu abri os braços. Eu não saí de lá eu disse assim, você tá derrubando isso aqui ó, mas eu não vou sair daqui ninguém me tira aí abriu os braços. E hoje hoje eu ainda tenho um.

Sabe de trabalho eu tenho o meu espaço muita gente correr todo mundo saiu ficou uma agonia você pensa assim, você não sobrevivi aquele canto ali, você trabalha leva o pão de cada dia para dentro de casa. Tinha uma filha que tava na universidade estudando e eu lá trabalhando quando chegou para derrubar tudo eu digo não ela olhou assim para mim, o que que você vai derrubar as escultura, porque meu marido fez com tanto trabalho com tanto amor de Tentação, tira tudo tira tudo. Só você só não me tira daqui daqui você não me tira eu aí no outro dia isso pode ir numa segunda-feira quando foi no domingo no sábado para o domingo todo dia que a gente trabalhava lá no bar. Eu pretendo coloquei uma lona uma lona preta debaixo e os crianças chegava chorava, se não há dor que eu tava sentindo entendeu? 40 anos a minha vida trabalhando ali, só que eu

Sim, mas a gente nem gente eu peço sim, porque quando vier a gente não desiste gente segue em frente a cabeça me segue em frente não tem que desistir não tem que desistir tem que continuar né? Mas vocês viram eu tô tranquila. Me aposentei com um pescador porque eu também cagava o coisa de pescador e cuidar logo cedo. Tirei carteira de pescador ele também aí eu peguei lá o cantinho dele para meu filho sobreviver de trabalhar, minha filha trabalha hoje eu tenho uma vida. Graças a Deus bem mais melhor de que essa que eu passei, né? Eu passei. Eu passei que eu não desejo para ninguém. Obrigado por você, meu depoimento agora é te agradeci também, mas alguém tava era você.


Tudo da máquina que é que embarcou aquela obra lá nós o que nós for embarcou aquela obra lá formar o dia baile, gramame eu fui lá junto com a gente e a gente passando quatro noites e quatro dias de vez em quando chegava a gente trazendo recurso trazia um pão trazer uma bolacha e a gente não como ela falou aqui não desistiu da luta, né? É forçando o dela não resisti não desistiu a gente não tem que desistir da luta. Não sei se é acompanhado de como é que está isso. Agora tá acompanhando tá o ministério público e a gente foi para uma reunião foi um uns dois meses e cacete faz medo né com com Funai e eles estão fazendo estão fazendo uma uma tô me entregando umas notificações para os donos de pousadas terreno. Que que estão na demarcação aí tá tendo. Esse estudo, né?


É porque é ver uma equipe de Brasília eh fazer aqui um trabalho de campo é assim que chama trabalho de Campo aqui para reforçar a o trabalho que Fábio Moura fez, né? Então vem essa equipe aqui eh visitando fazendas por aí e também os Empreendimentos eles exigiam assentamento do documento era como fosse uma notificação, né uma intimação, mas só que em relação a essa matéria é roubarão aí assim a aldeia a barra de gramame fez a reunião dela lá e tem sempre alguém que tá que não não fiscaliza sempre agora agora mesmo, ele foi lá então, a gente é o que fazer o reflorestamento aonde derrubaram as árvores, entendeu? E também a documentação também tá em


É tá com a com com com com já foi suspensa a a liberação, né? Até essa última agora que a o o ovo como é do do do do do do do do do do do da sudema, né? Eles liberaram esse documento, mas na verdade não era para eles ter já estava embalado, né? Então eles foram chamados por ter liberado esses documento aí então nós estamos acoberta, né pela aí pelo Ministério Público, né? E também é a dpu, né com através da do do advogado com o nome dele é um urso, né? Então tá embargado isso aí, nós estamos também fiscalizando também, né? Sempre tem guerreiro sempre dando uma passada lá, entendeu? Se acontecer alguma coisa de alguém entendendo? Eh tiver tentando derrubar as máquinas, a gente vai para dentro para cima e a gente já deixou já bem claro para todos.


14 que tiveram lá tentando derrubar e também para as autoridade que se a próxima vez que colocarem máquina lá dentro a gente vamos botar fogo na entrega mais não, tomo já decidido a isso aí tinha uma máquina lá que valia 2 milhões, ele disse e Nossa Máquina esse mais valor era essa essa mala que você tá derrubando aí quer saber de papel higiênico para mim e vale essa mata aí que você derrubou e quer derrubar o restante, né? E é de nós vai deixar a gente passou quatro dias lá filha, disse que pode pode de quatro noites e a natureza foi Primeiramente Deus a gente e a natureza quando a gente no último dia que Carlinho para todas as noites e o Cajueiro para ver se teu lado dos dois Cajueiro começou a chover, né? Mas antes eu vejo esse dia muita muita felicidade, né? Cara natureza da água, felicidade for falar na ponta da natureza vocês falaram na força da União na força da Resistência, né? Aí pode falar na força da natureza lá no sagrado da natureza.


Vocês que Vocês decidiram a contar por exemplo, nós passamos em uma aldeia que a gente viu o cavalo com a o seu o seu pelo aqui do lado, né? É todo implantado de uma maneira que Ninguém Vive. Sem tranças só se cortar umas florzinha então lá nessa Aldeia falaram muito de Comadre Fulozinha. Vocês conseguem vezes Encantados, né ver vendo com jogos percebendo que existem.


Umas blusinha para Palio Mangue uma entidade, mas tem pessoas que chama para perto, né? Que é mais uma conexão com ela, né? Aqui embaixo tem uma mata também tem uns que que que que são por mal é para o bem também tem a mata aqui embaixo que tem um pé de que faz caixão aquela madeira que pegava como ela ganhou Opa. Acho que uns 10 homens para abraçar ela e quando eu chego lá perto dela, eu eu fico muito a felicidade. Eu dou um abraço nela assim, mas não consigo minha vontade é pegar o meu abraço e porque uma árvore ela é muito boa, não é não é de é caixão era bem Uber o cara bate nela, faz boca o nome dela mesmo é madeira de fazer caixão mesmo é muito bonito ele e ela é grande. Ele é grande que eu faço assim é muito bonita e quando uma vez eu cheguei lá tinha uma abelha bem grandão assim, eu deixei ela quieta sair estão protegendo ela, né? Aí se ela fosse a natureza para mim aqui também professora tem um lago encantado que a gente chama aqui fica aqui, né? Você sabe explicar bem direitinho as histórias é Carlinhos. Deixa ele falou.


Do Lago Encantado do pescador, né?


Porque o pescador as pessoas passam não fala mas é a sobrevivência dele é no ar, né? Então assim história tem muita história e quando você vai plantar uma história de pescador, pode é pescador, né? Mas logo dormindo tá mentindo, não é mas eu não vi um dia para fazer um trabalho meu filho, viu? Hoje eu trabalho viu? O barco ficou é uma história com você ficou o barco ficou no canto e ele desceu com Marcelo ou é verdade? Não poderia contar essa história é só lembrar ele que é ele faz muito tempo então Marcelo. Fala aí procurou se o barco não tava conseguindo.


Do Eu lembro que as pessoas todas numa mergulho que eu dei assim da pedra no Rio Grande do Norte, eu não posso você tem passagem se você se você conversar com você, tá praticamente encaixador você acha mesmo. Quanto é aquela do tubarão aquela do tubarão com pescador? Ele vai acreditar. Geralmente quem quem não acredita quem não é quem não vai pegar porque ele não é caçador nunca foi na mata caçar aí na TV, mas se você disser para um caçador de Caçador de profundidade aí tá saindo mais bagunça aí até virar um professor, né? Aí tem um bar tem cinco pessoas assim os mergulhadores dois mangueiro e um mestre e daí eu ia matar os Seus cabos dele lá hoje quando eu vi é um monte de garagem Juba se chama.


Bonito que se aproximaram né? Eu vou peixe grande, eu nem fiquei logo. Eu sabia que ali ele vai atrás de um daqueles e é coisa grande ali, aí eu parei aí quando eu dei a natureza não precisa mandar nada a misturinha daquele desse tubarão, tipo. Tu é um martelo, né? Mas ela é grande, aí eu peguei e desci bem devagarzinho. Fiquei no chão paradinha, né? Ela chegou bem perto assim e voltou novamente, tá ligado? Aí eu fui devagarzinho que eu tô com uma safada de lagosta e subir aí disse rapaz no próximo barco aí deixa o barco perto aí porque ela gostou embaixo. Mas tem um tubarão aí disse que passou aqui perto do barco, mas é Aí eu deixei lá e voltei de novo. Fui pegar a bagunça lá, mas também não mexe. Não sei quando tá com fome bicho tá com fome vai lá na bunda daquele bichinho lá do meu cavalo, sequência da Fala. Tava dois Pessoas duas pessoas um dois tá? Você sabia que ia me falar alguma coisa aí Gorete começou.


Aí barco já entrou se dando caso dele, aí vocês dois estavam brincando de algum jeito não tava falando sobre a fã da natureza. Que sobre essa é manguba o nome da madeira que ela é bem rouca. Aí bate a terra faz um bombo. Ela é grande é grande mesmo uma vez aí, ela tem uma tomada aqui embaixo, aí ele tá falando que ela foi na natureza que estava protegendo na abelha, né? E a Lívia qualquer homem for violou aquela árvore. Eu eu acredito que a folha na natureza aquela abelha que ela tá caindo ali para ele, ele se sair tá entendendo? É que eu aprendi tá falando na natureza, é isso só quando a professora que fala sobre esse animal, né com esse negócio que se enrolou um dia que é com base. Não sei o quê, mas há quem diga que existe um morcego um morcego ele que faz esse tipo de trabalho que enrola o cabelo do do animal certo? Esse negócio é é espírito, ó lá sobre o negócio de espírito são uma coisa aí muito muito difícil certo.


Difícil porque existe o que existe crença, né? Crença existe também muitas também conto de fada no meio dessas coisas também certo, já que nós estamos falando assim, né? Vamos seguir alongar pelo uma experiência minha que eu tenho porque para pessoas estar às vezes inventando contando coisas aí por isso que eu prefiro ficar calado, porque eu creio muito assim no Poder de Deus porque existe Deus Criador, né, Deus Criador aí você fazer como é que eu vejo Deus que ninguém viu Deus a única pessoa que viu Deus quem foi seu próprio filho Jesus na época, ele se apresentou para alguns discípulos, entendeu? Então é aquela coisa eu não posso afirmar coisas certo que eu não tenho certeza certo porque eu às vezes estou assim certos canto e vejo alguém contando muito sobre essas lendas, né? Que


Aí pai do Mangue, o pai deles é João kalaf Comadre Florzinha certo então se você for biblicamente você vê que isso aí são as coisas eu indo pela bíblia certo que nós vamos falar em religião é como falando assim LG assim, né que é sobre crença. Então eu creio naquilo ali que tá na Bíblia, então isso existe coisas que existe sim certo, mas eu vou ficar calado porque um desse que traz proteção aonde hino biblicamente ver que são coisas mal. Isso isso é que eu vejo biblicamente biblicamente eu estou falando biblicamente me desculpa, me desculpa, mas aonde eu estiver que eu acho que alguém perguntar para mim sobre religião e a legião não é para ser discutida, mas sim para ser.


Falar da verdade e a verdade principal quem é Jesus certo? Tem um que viu ele um que viu o pai foi Jesus certo, porque existe Jeová que é Jeová como é que eu vejo Deus nunca vi Deus você vê Deus em que na natureza né? O vento desce, estou vendo Deus através desse vento. Tô vendo Deus através desta árvore aqui certo. Tô vendo Deus através de uma próximo que é você, entendeu? Porque já deu disse assim se vós não amar ao vosso próximo como pode me amar que não vê certo então se você quer fazer alguma coisa para Deus faça primeiro ao seu próximo, né? Eu vou ver Deus aonde Quem é o homem que consegue pegar um coco daquele ali e colocar água manter ali um coco ali dentro sadio uma água doce dali tem aquele processo que ele vai secando.


Perto dali, você vai colher um leite que serve para você preparar um peixe, né? Fazer não né? Que o peixe já foi feito preparar um peixe você vai preparar o que fazer ali uma cocada certo preparar um manguzá certo um suco e várias coisas aí então nós vimos Deus nisso aí que a natureza que a natureza é Deus a palavra Jeová significa o quê criador certo? É onde você vende Deus certo. Então eu creio nas coisas que concreta certo, porque coisas que eu vejo falando aí são coisas que assombram que assombram e quando eu lembro eu e Isaías meu irmão e eu nós íamos a gente moramos aqui em vários locais aqui e o pai Pedro Severo o buraquinho se desca bobo morou aqui em vários lugares aqui nós moramos aqui e então a gente foi morar na Jacó.


Mas já coca, minha mãe Iracema ia para uma casa de farinha k na na na na na na na na na na na tesoura na tesoura. Então eu já ia ficar ruim comigo de a noite buscar ela e trazer os beiju certo e no caminho. A gente via muitas coisas. A gente vê muitas coisas durante o dia na mata, a gente via uma boneca assim como fosse uma menina nos cabelos grande e nisso a gente se assombrado e corria e o menor saía maior mais forte pegada na minha mão você ia correndo a noite que a gente ia buscar a nossa mãe na casa de farinha a gente via aqueles vulto passando dentro de uma casa para outra dizendo que se assombrado e corria quer dizer coisas que é de Deus você se alegra certo, não sei que concordar comigo, mas eu acho assim. Acho que tenho certeza aquilo que ele Deus aquilo que aparece de Deus para você, você se alegra certo tem relato na Bíblia quando o homem Deus para fez algum movimento.


Caí ali certo e nem quem quem quem quem não sabe a história de de Saulo que hoje é o que Paulo de Tarso. Vocês que são formados se formou se formaram que nem padres e outros e outros acreditam que você leu a briga, não é isso você para se formar em alguma coisa vocês leram a Bíblia porque ninguém passa em certos cursos aí se não tiver cursos teológico, se não tiver experiência é biblicamente para se formar em um curso aí teológico de Padre tem que passar pela bíblia certo. A Bíblia é o que a bíblia ela diz assim não a Bíblia só uma não, mas existe vários tipos de Bíblia existe o que também existe quem isso aí chamado do que senta que nem tem Testemunha de Jeová simplesmente Jeová que nem eu disse o único que foi testemunho Jeová quem Jesus até porque Jesus disse sede de mim é testemunha, entendeu? Testemunha de Jeová é Jesus então Há Uma Saída de Deus.


Manda Jeová pega a bíblia e traduz da maneira deles certo existe uma tal também de mórmons, entendeu? Morno também são que se senta eles pegam uma Bíblia são diferentes tem um líder chamado Joseph Smith, eles pregam isso aí, nem que os discípulos apostaram e bota Josi fez Meet é então parte de religião, me perdoe que eu conheço que eu sei certo são essas partes aí que eu não vou estar inventando conversa do mato disso daquilo outro que me apareceu certo e me assombrou é porque existe muitas essas coisas quem morou em Mata que morou em Mata em Sítio, já viu muitas coisas certo berrado de morte morde correndo atrás certo. Aço veio que nem Samuel meu irmão na época, meu pai, a gente fazia carvão à noite ou melhor fazia carvão, quando era noite ia puxar a pessoa tava frio. Quem quem fez cavava o faz.


Muito bem que às vezes você precisa daquele carvão antes, aí você tem que tirar aquela camada de terra de cima e Vai socando aos poucos para que o fogo se apague geralmente para você colher o carvão e tem o cheiro do trabalho que a gente fazia à noite e muitas vezes o papai dizia Samuel fiquem aqui que eu vou ali no rio buscar água samba eu ficava ali no momento que papai ia no rio no ali buscar água lá vinha Samuel. Assombrado gritando, o que foi o mato de florzinha subiu no meu ouvido eu corri doido aqui quer dizer se é coisas boas, você não se assombra, né? Isso é coisas boas, você vai abraçar sem o espírito de Deus bom você vai se alegrar. Porque existe sim existe quem não sabe a rebelião que houve no céu contra os anjos de Deus e os anjos de diabolo que desobedeceram a Jesus já viu a história de Adão e Eva no Jardim do Éden.


É e Deus fez o homem colocou no Jardim do Éden ali então quando eu quando foi visitar o homem ali já dentro do Éden o homem estava no há quem diga que eles comeram que Deus disse não comeram do fruto do conhecimento do bem do mal. O pessoal tem uma uma simbologia que uma maçã não é uma maçã certo era um fruto ali que no momento que você comesse você ia ver a nudez certo, você ia ver é a falha no seu irmão, você vai ver o que é nudez aí viu? A voz de Deus disse Adão Adão Adão. Onde está aí ouviste a minha voz ouve senhor, mas estava no estava mesmo começo do fruto que eu disse não comeram e uma mulher que tu me desse como esposa como eu dou puta me deu e eu comi então ver aquele procedimento da Terra o homem agora vai passar a ser sobrevivente da terra, mas vai trabalhar com com com com com dignidade com sofrimento para adquirir o pão a mulher ia.


Filho porque Deus disse multiplicarei eu sempre o submundo da tua gravidez então quando se aumenta é porque já tinha quando Deus disse aumentarem é porque a mulher era para ter filhos, mas não era para ter dor então depois desse pecado tudo que houve aí que essa é a serpente como nós fala nós se pintamos a malha da serpente é o que né Lucas falou, mas biblicamente para Deus é o que a serpente do mal é o que a serpente é coisas mal certo. Não tô criticando lei de eh, eh, eh cultura que eu também sou indígena não tô certo. Apenas eu tô comprometer eh, eh eh eh eh explicando melhor certo para que nós não vivemos enganado, mas a simbologia da serpente não é que ela é boa é ruim quando uma pessoa ver uma cobra uma serpente que é que se eu ver uma coisa que ele não vai pegar o que um pau e matar eu não quero proteger eleger eh.


Modo nenhum é uma serpente então eh eh Resumindo isso aí, né? Para não prolongar tanto né? Que a história aqui que eu tô falando pode não tá agradando Há muitos mais, essa é a verdade, viu? Professora. Muito obrigado pela sua idade todo o respeito a qualquer um qualquer coisa a minha mãe eu faço foi tipo minha mãe porque minha mãe que me excluiu, minha filha é assim da minha mãe, minha mãe disse que meu que meu avô ia para um caminho muito assim muito escuro aí viu um negócio fazer assim para ele assim é um lobisomem. Ele pegou e ficou lá travado, sempre foi pra frente ele para trás quando vai ser o dia professora ela a fazer o número, mas esse simbologia da serpente não quer dizer que ela seja boa assim ruim é que quando teve a invasão do Brasil no a invasão no Brasil, nós se escondia muito encerra em Montes Alto era um dos portugueses. Não entendia muito em serpente. E essa ele tinha muito medo de serpente.


Entendeu agora, aí ele não ia subir numa Serra onde ele não sabia daquela serpente aí simbolismo da serpente. É por isso não é dizer que ela protege a gente ela sabe que se a gente for pegar ela ela vai picar entendeu? Então quer dizer que ela é uma simbologia de sagrado ou alguma coisa assim, é que eles tinham medo e para não chegar até nós o simbolismo da serpente ficou proteção. Entendeu? Agora não quer dizer que ela é boa. É minha irmã, eles preferiam não quem é que sabia de uma serpente Cascavel, eu queria lá e lá fora é isso aí, então nós quer dizer que ela é um livro, entendeu? É para encerrar nossa nossa conversa se alguém mais também quiser falar e seja à vontade e a gente tava no tópico da espiritualidade já né? Então Eh sobre a diversidade de rituais. Eu quero a esclarecer daqui quando a gente tá falando em rituais. A gente não tá falando.

Rituais eh de umbanda rituais de de um culto rituais de não não só disso né? Mas rituais aquilo que se tornou-se rito, por exemplo um pescador quando ele vai para pescar ele tem um Vip anterior a entrada no mar ou no Rio, né? Que aquele que geralmente vocês fazem ou uma caçadora quando vai para caçar tramada antes, ele tem um rito um ritual de preparação, vamos dizer assim então. Vocês poderiam falar um pouco disso para a gente encerrar a nossa conversa de hoje de manhã, quando eu vou eu sou cristão, né? Quando eu vou para o amarelo, né? Eu vou fazer uma pomada de fora, eu peço muito peço proteção a Deus, né? Porque lá tanto faz a gente ficar com a janela aí em cima ou o barco como tá embaixo no terceiro andar.


Filmar ela é assim e só Deus levar a gente para Deus para trazer é onde a gente pede minuto é muita proteção a Deus é porque na verdade professora que nem a senhora tava falando aí que nem eu já falei é isso, depende muito da crença no que a pessoa tem é que a pessoa tem eu respeito a religião de todos, né? Porque cada um tem sua religião e cada um pede de acordo aquele ritmo que ele segue certo agora na verdade mesmo. Quem protege tudo aquilo que você pedir a fulano ou assim grande é Deus, né? Então aquela coisa bota Deus primeira da frente Deus tô indo aqui nesse barco aqui nessa pescaria aqui me abençoa Que Eu Vá e volte, né? Para mim é assim ou no caso vou casar caçar ou pescar é o vice-versa, entendeu? Eu farei isso aí pediria a proteção a Deus porque é diretamente não existe intermediário, entendeu? Não existe.


Que você pode ter você não sou um caçador, eu sou devoto de fulano, não tem isso, né? O disciplina você vai pedir aquilo ali, mas na verdade quem é que manda chuva tem que mandar chuva para nós Deus mas você pode eu vou pedir chuva a quem a São Pedro. Ah tá chovendo. Eu preciso de lavar uma roupa ou fazer um fogo vou pedir para São Pedro parado, não é isso? Você não veio isso aí, mas quem é que manda chuva e manda só é Deus tá acima de tudo, viu? Desculpa mais uma vez alguém mais alguma fala é tudo depende da fé, né? Então fica melhor essa tua fala na sua vida, mas se você não crer, né, se você anda no caminho e você vai com Deus.


Ele vai vir mas quando você andar com medo, você é depois eu nunca pode comer que nem ele vai rolar mais um pouquinho só um pouquinho só é a receita, né? Um monte de 3 horas da manhã, parece na boca da Barra. Aí pescamos de 3 horas da manhã até 8 horas do dia tá todo mundo desgastado hoje 9 pescador tudo desgastado, aí desistiu doido aí se o pessoal vamos dar um lance ali eu garanto vai vim cara, esse aqui que eu ia pegar peixe, isso fez a gente ia pegar desse tamanho eu disse desse jeito eu não dava lamentar nossa família. Pescaria vai pegar muito peixe. Aí chegamos lá nesse lugar numa boca de barra. Tava assim de menino brincando com tomando banho aí o outro eu disse a você querendo não ia pegar peixe já ó que a gente tomando banho, mas ele pega os meninos não vai pegar os peixes aí jogou uma rede com muita fé entendeu, né? E Deus concedeu a cabeça dele o Paulo tá então esse menino aqui ó, não sei se vai aguenta.


Lá do lado grande foi assim muito grande nossas férias não fodeu. Isso aqui é uma festa Ok como desistiu dois, né? Foi só o restante é lá a gente dividiu o peito do pessoal que não tava nem pensando né? Pois bem agora tentando finalizar mesmo e ao mesmo tempo querendo aproveitar o conhecimento do Artesão que tá aqui é ele né? Com artesão essa carranca, esse aqui é feito de casca de Fale para nós sobre o sentido dessas Carrancas, casca de cajá, tchau.


Indígena cada carranca e essa carranca tá simbolizando os indígenas em geral ou o povo Tabajara todos todos todos todos ela ela ela ela ela expressa o que é a maioria das pessoas o olho grande é virar espantar os maus pode mandar uma mensagem na frente de casa, meu amigo, porque os pescadores antigamente não era ele eles usavam nos barco, né? Muito grande né? O olho grande então é um símbolo de proteção, né isso embora ninguém nega a fé, mas a fé também tá no símbolo do processo é verdade?


Ah, cristianismo chegaram no Brasil os indígenas porque hoje ainda tem muitos que não chegou nos indígenas, mas a a proteção que eles tinham era era do Sol dos Terra desmata, né? Cada cada um ele ele se expressava com dois Tupan e se expressavam dessa forma aí que foi quando chegou Portugueses e evangelizou vários povos indígenas, né, gente então eu acho que deu para a gente visualizar um bocado de fala de vocês, né? A gente tem aqui muito material para trabalhar. Pretendemos mais ou menos depois e depois do dia 21 de julho. Possivelmente é que a gente começa a retornar lá pela por vocês vai fazendo o ciclo de novo para que aí a gente vai trazer em gráficos, né, Ó gente os resultados dessas bem em relação aí.


Fazer essas quatro catei essas três categorias foi isso assim assim. Aí vocês vão dizer bateu bateu com o que a gente falou a professora não ela não tá muito longe do que a gente falou aí a gente retoma e se chama validar a pesquisa. Aí a gente vem para essa etapa de validação. Tá certo? Tá só daqui mais ou menos um mês e pouco. Aí a gente volta a convidar, né? Eu acho que eu vou deitar na sua dispensação, né? E isso aqui nos aguardando é assim que a senhora puder viu, gratidão a presença de todos tá? Muito obrigado. Vamos aqui é fazer aqui uma foto aqui, né com a equipe aqui, nós vamos fazer uma foto de todo mundo aqui e equipe colocar bate uma aqui comigo aqui.")
contaPalavras(linhas)

write.csv(linhas,"26maio10.33.csv",fileEncoding = "UTF-8")
 