
install.packages("dplyr")
library(dplyr)
a=select(data.frame(Ald_aVitPerguntas$Column1.1,Ald_aVitPerguntas$Column1.2))
Ald_aVitPerguntas
data.frame(Ald_aVitPerguntas$Column1.1)

table(Ald_aVitPerguntas)
apply(Ald_aVitPerguntas)
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df2= data.frame(table(Ald_aVitPerguntas$Column1.2))
df1= data.frame(table(Ald_aVitPerguntas$Column1.3))
df1= data.frame(table(Ald_aVitPerguntas$Column1.4))
df1= data.frame(table(Ald_aVitPerguntas$Column1.5))
df1= data.frame(table(Ald_aVitPerguntas$Column1.6))
df1= data.frame(table(Ald_aVitPerguntas$Column1.7))
df1= data.frame(table(Ald_aVitPerguntas$Column1.8))
df1= data.frame(table(Ald_aVitPerguntas$Column1.9))
df1= data.frame(table(Ald_aVitPerguntas$Column1.10))
df1= data.frame(table(Ald_aVitPerguntas$Column1.11))
df1= data.frame(table(Ald_aVitPerguntas$Column1.12))
df1= data.frame(table(Ald_aVitPerguntas$Column1.13))
df1= data.frame(table(Ald_aVitPerguntas$Column1.14))
df1= data.frame(table(Ald_aVitPerguntas$Column1.15))
df1= data.frame(table(Ald_aVitPerguntas$Column1.16))
df1= data.frame(table(Ald_aVitPerguntas$Column1.17))
df1= data.frame(table(Ald_aVitPerguntas$Column1.18))
df1= data.frame(table(Ald_aVitPerguntas$Column1.19))
df1= data.frame(table(Ald_aVitPerguntas$Column1.))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))
df1= data.frame(table(Ald_aVitPerguntas$Column1.1))

apply(df, 2, function(x) { x[ is.na(x) ] <- ''; df})
#essa linha abaixo retira os nas do dataframe Aldeia_Vitória_Perguntas
modified_data_frame <- replace(Aldeia_Vitória_Perguntas,is.na(Aldeia_Vitória_Perguntas),"") 

modified_data_frame
is.na(Aldeia_Vitória_Perguntas)
a=na.omit(Aldeia_Vitória_Perguntas)
a
ibrary(dplyr)

select(Aldeia_Vitória_Perguntas$Column1.1,Aldeia_Vitória_Perguntas$Column1.2)
