
options(max.print=100000000)


contaPalavras <- function(linhas) {
  palavras <- strsplit(linhas, "\\W+")
  todas <- unlist(palavras)
  contagem <- table(todas)
  contagem[order(-contagem)]
}
linhas <- c(
  "A gente pega elas são a todos para gravar. Tá certo por conta da que a gente vai fazer a transcrição depois bom dia a todos e todas Bom dia nós estamos aqui hoje, né nesse encontro aqui com o nosso professor Tânia dando continuidade aos trabalhos, o qual já iniciarmos né? Logo mais ela vai falar de todo o projeto e a importância de tudo que está acontecendo e o projeto que é feito para conosco e para todo povo indígenas. Então a professora a senhora já tem a sua oportunidade para dar continuidade. Apesar de nós. Tamos ainda faltando uma pessoa mas vai dar tudo certo. Ela já está chegando dizer que é uma satisfação muito grande poder estar retornando e continuando com esse trabalho de pesquisa. Como foi dito uma vez anterior a gente essa é.",
  "Que faz parte também do apoio da da LPG, né do Paulo a lei Paulo Gustavo que a gente pretende mais adiante conseguir mais recursos para continuar com o estudo porque a ideia no final de tudo é que a gente tenha um mapeamento uma cartografia das condições de sustentabilidade, né? Seja nos aspectos mais fortes ou mais vulneráveis, né da existência de vocês, né? Então nesse trabalho nessa pesquisa e neste momento especificamente a gente vai trabalhar com uma uma dimensão apenas desse estudo da de um termo chamado resiliência socioecológica. Não se preocupe em entender isso a resiliência é nossa capacidade de sofrer. Eh pressão intacto que seja mas a gente retomar a gente a gente sofre mais a gente volta as regras isso é resiliência.",
  "Né e sócio Ecológico que é no sentido social e o Ecológico meio ambiente, eu tô ocupado por isso por isso que hoje só explicando ao grupo a gente vai focar especificamente na primeira dimensão que é o sistema de crenças, porque essa é a primeira dimensão, porque tudo parte das raízes de um povo, né? Então o sistema de crenças é a dimensão que está lá nas raízes de um pouco e nessas raízes onde são os valores. Onde estão a a a a a aquilo que dá sentido à Vida deste povo o que vai dar sentido ao que tem dado o que dá e o que dará sentido a luta de vocês para confirmar consolidar a nossa existência a existência desse povo como povo indígena Tabajara no estado da Paraíba certo as outras dimensões que",
  "Para ter ele falar e pesquisar e é uma luta conjunta. Nossa e necessária e a gente vai correr atrás de recursos para isso É voltado para as mudanças na biodiversidade Jaciara falando para mim eu já visualizando com a riqueza que vai funcionar nessa outra dimensão das mudanças na biodiversidade é o sistema produtivo de base primária propriamente dito fase primária e a governança o sistema de governança que é onde entra umas políticas que da outra vez a fala de Jaciara. No início, eu já navegava no sistema de governança de vocês aqui, mas a gente precisa levantar tudo isso junto com vocês enquanto a natureza de pesquisa, né? Diferentemente de um trabalho como o que já fizeram está coordenando agora na parte de produção audiovisual que também traz muitas informações e que poderá servir e documentário a ser consultado.",
  "Nas etapas e a e até mecha também Jaciara, pelo que você tá dizendo então a gente pode estar consultando e colocando na bibliografia, né? Esses documentários que a gente está consultando para fundamentar esses estudos, tá? Então primeiramente é existe uma breve apresentação no roteiro que nós fizemos porque algumas pessoas por exemplo a Valmira não estava presente da outra vez, né? Mas se ele é uma um nome rapidamente uma apresentação, depois eu vou falar para vocês sobre a necessidade de três assinaturas, vocês vão assinar é só se não quiserem, mas vocês estão aqui me indica que é que querem né? Três papeizinhos uma é uma frequência de vocês aqui e dizer o perfil já Senhora de cada um ao lado é importante para nós e o outro é o termo de produção audiovisual o produto de produção. Não influenciada por ela.",
  "Imagens de autorização de uso de imagem que é o que a gente tá tirando foto e no relatório vai constar alguma imagem. Então a gente vai pedir permissão a vocês faz parte do que é cobrado, né? Vamos dizer assim pelas instituições que fomentam né a Secretaria de Estado de Cultura, né? Ou seja, quem for comentam qualquer estudo nesse estudo. A gente precisa pedir permissão para tirar as fotos e depois é um termo de consentimento livre esclarecido que vocês vão precisar assinar dizendo que estão de acordo com a pesquisa em rápidas palavras então de acordo com a pesquisa e que a e que assina. Então tem um lugarzinho. Onde vocês vão botar o local da Aldeia podem botar até abreviado, né? Para não escrever muito mas abreviado desde que você é nova tá 4 né? Para a gente saber que a nova Taquara e eh assim e eu assino como",
  "Coordenadora proponente responsável pelo estudo tá então podemos começar do Cacique assim.
A respeito do nome e sua função nesse estudo aqui seu papel pronto bem como tu já me conhece, eu sou o cacique Paulo Tabajara que estou cacete na aldeia, Nova Conquista Taquara e estamos para contribuir no que for preciso.
Meu nome é João. Osiris eu sou advogado. Tô como estou na equipe como apoio jurídico tá tanto para esclarecimento de dúvidas de processo já existentes ou qualquer problema jurídico que eu possa ajudar com toda a equipe aqui certo então Agradeço o a recepção de todos novamente a segunda vez que eu venho aqui e o que eu puder ajudar poder contar comigo certo? Me chamo Moisés Andrade Souza, sou professor de educação física também, sou estudante do mestrado profissional educação, inclusiva eh, estou aqui na pesquisa como pesquisador voluntário, mas especificamente voltado ali na parte eh de um levantamento de um mapeamento das pessoas com deficiência que existe dentro do povoado e das aldeias indígenas. Muito obrigado.
","Viviane eu tenho a função aqui no projeto, eu sou a pesquisadora de apoio, né da Coordenação. Então eu fico aqui vocês vão ver só eu digitando aqui. Hahaha, mas eu tô aqui focada porque eu tenho que dar esse apoio no sentido tanto da coleta dos dados como também depois no tratamento dos dados e depois para dar uma resposta aqui para a comunidade. Então a minha função é essa tá pesquisadora de apoio, meu nome é Valmira. Eu também sou pesquisador de apoio. Vou ajudar na coleta dos dados análise e depois na apresentação dos dados Lima da Silva uma conhecida aqui na Taquara como um coelho som da jovem liderança. Bom dia meu nome é Rosinaldo. Sou aqui me entregando aqui da nova conquista. Taquara e satisfação imenso tá hoje aqui com um
Pequeno a parte do meu povo eu perguntaria no perfil, você traria como na no estudo assim no seu perfil, jovem liderança. Rinaldo seria pedreiro porque ele tem uma filha ele é uma faz tudo, mas seria alguém da construção, isso já construção.",
  "Meu nome é José Inácio Ferreira faz parte da nova conquista viva aqui para mais de 300 anos, minha família, meu pai, minha mãe tudo é daqui de dentro. Então faço parte desse grupo. Eu quero que cada vez mais cresce no nome do Senhor Jesus e nós vamos à luta, mas continuando a luta não pode parar, né? Esquecer algo importante é meu nome é Cláudio. Palmeiras é tudo verde, eu acho aí o perfil dele, ele tinha terminado como Caçador agricultor, o meu nome é Cleonice Alves dos Anjos Tabajara para mim um prazer e uma alegria estar no meio aqui de vocês também. Nós se aqui me criei vou fazer 80 anos. Criei minha família toda aqui tudo são minhas família tenho mais já com uma quase toda a família dele.
",  "Eu criei pescando tá trabalhando na agricultura tá aí criando meus filhos então aqui né? Graças a Deus ainda com essa idade. Tô aqui galega e feliz porque tanto medo de nossa família que vocês são uma família só né? Somos nossas famílias, né? E a mão fêmea professora foi pescar e trabalhada agricultura justamente com os meus pais, né? E depois você faleceu. Mas continue trabalhando e Continuo trabalhando ainda. Tô cuidando. Mas continue plantando trabalhando ainda é Deus abençoe e que Deus abençoe e é também liderança social. Nossa aqui viu? Ela vai entrar com a liderança. Bom dia meu nome é Jefferson. Sou filho do cacete linha de frente da segurança do meu pai aqui eu demais parente da segurança o perfil segurança que a gente tem que ter né? Os parentes que quando a gente tá nas retomadas.
Sim, é importante nos movimentos de rua. Tem que ter essa pessoa com esse olhar também, viu? Isso muito bem já posso dizer o meu nome moderada atual atual, meu nome é Katiane Alves dos Anjos Rodrigues e arin Tabajara, sou enfermeira de profissão. Sou pescadora também de profissão e estou aqui como uma pessoa deficiente da inclusão, né de deficiência, eu sou deficiente visual, traz monocular.","Lembre de design de nascimento Tabajara, né? Que eu mandei botar no meu documento e sou nascido e criado aqui dentro de Jacumã, pescadora pescadora e quarto parte desta família meus pais era pescador, minha mãe tinha roçado, eu também trabalhava no roçado e estou aqui de pé.
","E parece que gostava mais da Pesca gostava mais da Pesca. Pesquei aqui essa Jacumã todinha até na barra de gramame que a gente ia pescar em Tambaba naquelas pedras para pegar era tu.
Tem história a gente conheça aqui as pratos esse povo falando sobre Universidade vai ser o show aqui em Maceió pegando peixe no Maceió, camarão, a gente abriu os Maceió para pescar não é? Eu só mas vocês não estavam na turma. Eita, vai abrir o Maciel para pegar os peixes de Maceió e tem essa turma cantava não cantava. Como cantar e cantava dançava funk dançar a pastora e dançava Lapinha, você não foi trabalhar hoje tudo isso quando eu começar aqui falar das danças vocês viram de novo, tá? Obrigada vocês estão Anotando os nomes de cada um uma lista. Eu me chamo.
Esse Alves dos Anjos Oliveira Tabajara, sou pescadora agricultura e faço parte do Conselho eh local da Saúde indígena tem duas aqui no perfil de saúde, né? Uma nova conselheira e a outra enfermeira eu sou Tânia Tânia Maria de Andrade, né? Nome de guerra Tânia Andrade e filha de agricultor.","Neta de indígena agricultora, né e professora aposentada pesquisadora Nativa continua na ativa até quando Deus quiser exatamente e muito feliz, toda vez que eu venho para cá, viu? Me sinto muito feliz honrada de poder estar compartilhando, né ideias ouvindo aprendendo com vocês, né? Me sinto muito feliz. Obrigada. Bom dia meu povo, sou Jaciara Costa Maciel Tabajara mais conhecida como Jace Tabajara, sou liderança de mulheres. Se eu lhe der nosso indígena sou anda dança de mulheres, né? Sou mãe atípica, sou gestora e produtora.
","Plural fiz um curso de Antropologia que é antropologia ela me atravessa em tudo isso mas eu coloco sempre como a última coisa que às vezes eu penso que eu nem exerço e é Talvez seja a primeira coisa que eu faça na minha vida é antropologia eu fico eu fico nessa se eu coloco como a primeira ou como a última situação e no mais a gente tá aqui para contribuir com essa pesquisa com esse projeto que é incrível e muito importante para nós então pronto fechamos essa primeira rodada de apresentação, nós vamos agora para a parte mais assim de assinaturas. Tá Google, eu quero tem uma uma um documento aqui pequeno, na verdade é pegando o nome de cada um eu botei até 15 pessoas porque como é frequência dessa rodada a equipe de apoio a pesquisa também é assim, mas assim preferencialmente até.
Depois ou 11 primeiro que tiver seja do grupo focal que a gente tá trabalhando. Depois a gente assina após eles né? É o nome e o perfil do participante do colaborador porque a gente pode contribuir anotando nós mesmos gostosinha, eles põem os Neves e a gente escreve aqui tá certo? Vocês colocam o nome de vocês se inscreve aqui depois que a gente tá a gente discutiu que seria mais prático já vai levando as três folhinhas aqui já assim assina assim, né? Entendo para a gente ganhar tempo, depois tem um termo que é chamado termo de consentimento livre esclarecido e o outro também todo esse material que vocês estão assim lembrando gente, vamos ficar guardado nos meus acervos pessoais, porque essa é uma pesquisa que a gente não é para o IFPB, né? E a UFPB é para nós, né junto com a seculta que a secretaria de cultura esse material vai ficar comigo.","Cinco anos guardadinho arquivado. Porque qualquer necessidade. Se for para consultar quem é que estava quem quem não estava alguém dizendo não, mas eu eu tava lá no grupo e não mas Professora Tânia, deixa a gente ver aqui quem é tá aqui tá? Você já tá tudo documentado que estas pessoas também que aqui estão serão elas que quando na próxima volta que a gente der com vocês já vai ser para validar o que esta Aldeia pensou. Então conforme a gente vai discutindo. E tratando os dados, né? Por Aldeia, inicialmente a gente vai precisar voltar para vocês dizerem É isso mesmo ou não? A gente a gente acho que precisa melhorar nisso, a gente chama isso na na pesquisa de etapa de validação dos dados na nossa próxima volta é para essa validação por isso quem tá fora que queira vir tá pro
Vi não, pode vir mas na hora de decidir se aquilo que foi dito tá correto, se os dados batem são vocês os que estão aqui que vão dizer bate ou não bate aí a gente considera que na aldeia x já os dados foram validados na outra Aldeia para No final a gente usa um um é um equipamento um software para poder cruzar os dados e a gente gerar é o que a gente chama de núcleo de intercessão, né da do sistema de crença, porque depois a gente tem um núcleo de intercessão do do sistema socioecológico completo então, por isso que é uma pesquisa complexa, mas ao mesmo tempo de cunho de profundidade, tá então esse termo de consentimento livre esclarecido, ele tem um texto relativamente grande, mas fala do nome do projeto para eu.","Muito tempo landeiro todo tá? Fala do nome do projeto por quem está sendo coordenado que é por minha pessoa tá? Tentou essa equipe de apoio que inicialmente a Jaci foi convidada, mas ela não pode mas assim gostaria muito que ela já estivesse na próxima etapa como membro oficial da pesquisa também, né? Porque você é uma antropóloga e aqui como o trabalho não é para visão apenas em antropólogo. Mas quem tem uma leitura sistêmica de tudo você tem essa visão essa colaboração e não precisa necessariamente. Você tá vendo que a outra Aldeia não venham aqui o outro também por cada um com seus motivos, né? É festa, não sei de que é quer tá comemorando o aniversário do Dia das Mães, daí isso tá aqui todo mundo tem seu motivo, então na próxima etapa já assim mesmo que você fique. Olha eu tô como pesquisa.
Colaboradora da minha Aldeia. Então tá já tá já consta tá, né? Já está eh os riscos e benefícios aqui a gente diz que não tem nenhum risco para vocês, né? Por nós não é a gente não tá tratando de uma pesquisa que vai mexer com dados genético, os que vai mexer com algumas situações de riscos para a saúde de vocês então nada disso certo o sigilo Anonimato e privacidade é o que a gente reza aqui nesse texto dizendo que a gente garante por esse termo a gente tá garantido sim no relatório nos artigos que possam sair dessa pesquisa, tiveram alguma informação que vira o sigilo da gente das informações aqui a gente tá vamos dizer assim sujeito a passar por algum processo que qualquer um pode dizer assim não a gente a pesquisa é menta.","
Né, a gente não valoriza, a gente não disse isso então, esse é para garantir o sigilo a ética né das narrativas quando a gente vai colocar eh algumas narrativas nós nós não vamos estar botando nome de ninguém para não comprometer ninguém, mas por outro lado eh no relatório da pesquisa para valorizar. E ser ético também a gente vai colocar os colaboradores indígenas que são todos que estão participando desses grupos focais aí o nome completo por Aldeia. Tá certo? Então é uma questão médica, a gente autonomia tá? É para dizer a vocês que vocês tenham autonomia de dizer não não queremos participar desse estudo ele não nos interessa também tá certo? Não assim dá nada ou tá participando e de repente diz assim, rapaz, eu não quero mais não, então autonomia você pode dizer.
Só dizer Professora Tânia a gente eu sair da da pesquisa. Eu não sei a gente só vai tirar e pronto tá certo devolutiva dos resultados. A gente tem um compromisso de devolver. Esse resultado é tanto que a gente vai eh, vamos dizer nós vamos eu falei para vocês da Etapa seguinte que é a a validação dos resultados. Vocês vão validar para nós esses resultados se batem porque nós estamos interpretando bato com o que vocês estão dizendo. E o consentimento da participação eu aí vocês eh, a gente pode botar até o nome de cada um aqui só assina, você só assim não tá certo, então é quem poderia passar aqui nós temos o termo vou passar seis viver para um e seis para outro, né? Não é melhor e tu me dá a lista que daí depois essa que eu vou passando a lista de presença que você já.
Calma, ó, o perfil pode deixar que a gente coloca tá o termo 4. Acho que isso aqui tá bem firme para assinar, né? Seis ó, já você já vai passando para cada um é acidente, tá bom esse aí para ensinar ou tá muito ruim muito bom. Pode vir para para mesa coelho pode vir para mim. Fiquei curiosa de querer saber porque Coelho eu sou menina me perguntando o coelho é a família dos Coelhos. São todos da família do coelho a gente acaba chamando do coelho não tem nada a ver com animal com ele porque olha só o Imaginário eu fiquei pensando. Meu Deus, será que eles criaram uma coisa era o avô dele que chamado seu coelhinho.","E o neto do seu coelhinho, os outros é os coelhos, né? Como os anjos da família pelo tronco a gente essa aqui é melhor Família dos Anjos e coisas diferentes aí ó, vocês podem assinar aqui tá? Tem mais caneta aí, mas é isso eu trouxe meu filho. Olha aqui só a assinatura de vocês, tá certo? E a assinatura É aqui, ó, não tem problema não, esse Jefferson ele não assina tá vai deixar apagar eu vou passar agora o termo da autorização, tá?
Jornalista não sei problema tem quantos desse faltando só foi Cleonice e Zé foi desse aqui, mas Elson e Ronaldo perfeito.","Escrever se você escrevesse é isso não é uma poeta pode publicar aqui a foto do coelho também. Moisés o coelho né? O Corinthians no final é claro que sim. Pega com coelho. Acho que tem que ser só um apoio viu pra ele e eu não tenho medo pronto, o senhor pode pro outro botar o dedo aqui pode não pode ligar ele tá muito grande não tem nada não sobrou. Qual a data de hoje?
","Pode mandar limpar pode não chegar você quer uma padaria não tem esse aqui é o tema maiúsculo de imagem aqui em cima, vocês prendem a gente não tem certeza que tá tudo bem. A gente vai ter o nome pode botar esse aqui que a gente só pega o super-herói. Tem um documento aí que aí a gente colocar aqui, vou só aguardar a caneta chegada.
R r. Eu pronto aí a gente pode a Cilene dos Anjos Nascimento Tabajara, não é isso depois sou eu que assino aqui eu só tenho livre é o termo precisa dar o total do número de pessoas aqui, viu? Vou assinar rápido, olha o Palmeirense.
Vocês viu a caneta terminou Aí para dar fruto, aí bota no local, bota aqui é a aldeia tá com nova Taquara, né? Uhum. Eita, eu botei Conde Tem nada não meu Deus, eu botei aqui ó, esse é o que demais.","por favor, coloque cebola põe a colher mais bonita, mas é
Eu só tenho que assinar o dele e vou deixar aqui porque ele poder guardar. Ah porque eu não vou deixar não, foi porque ele pensava que se eu tivesse olhado ele ia assinar tudinho É Só Começar a se empurrar de doer só para aí empolgou. O que é a mesa a senhora tem apoio é melhor assinatura assim eu Cleonice dá para botar em cima pequenininho e esse aqui embaixo e ele conseguiu chegar perto de todos, né?
Não se tá batendo tudo Tabajara algo.","
Sim, aqui é é a data essa era a bota 26 normalização do uso de imagens para conhecer constantemente, né? Zero cinco seis sete é 2024 agora dois aqui falta quatro zero o termo né dois de novo o Palmeiras e quatro sentimentos e a frequência também.
Ah, a caneta tá aqui. Obrigado, viu? Cleonice a l né? Agora eu vou ver mãe o meu é e o s Alves dos Anjos Paulista de presença fechou Jeferson e só é as três assinaturas. Obrigado, viu? Só isso mesmo agora tem a outra pessoa.
Sabe Tu sabe o CPF de mãe tem que pegar uns clipe tem problema não respondeu aqui, mas não se preocupe não, manda depois eu passo para eles não usava só ela assinar, né? Nesse local aqui é Jacumã, né aqui de novo Cleonice Alves Alves.
A percepção que muda do monocular para aprendermos. Agora se vocês colocarem a mão aqui ó, se Vocês conseguem observem, né? Esse lado aqui eu não vejo mas se eu boto aqui assim ó, já começa a ver então é reduzido é mais ou menos ao invés de eu ver sempre 90, talvez por 145, né? Além disso a percepção, tipo três dimensões é percepção 3D prosperidade. Tem coisas que a gente não consegue enxergar como vocês entenderem? A gente vê isso aqui normal, mas se tiver alguma coisa de profundidade, não sei se você sabe aqueles filmes 3D.
Que pega aquele jeito. Isso aí a gente não enxergas primeira faculdade zero ainda mexe com a gente da intenção que a gente tá dentro do dos espaços, mas aí agora deixa eu só faltava ela de novo da imagem não da imagem você vai participar.
Muito obrigado pela um acidente que você fez com que você sabe disso, só eram dois papéis e uma lixadeira frequência é obrigado você está Você já viu já veio filha é a visão normal dela, tô entendendo. Com certeza com saudade aqui. Ó, essa aqui é segura rapaz na faculdade na escola dos Anjos.
Então vamos com isso aí que tá fazendo aqui, a gente tá tirando foto valorizar. E esse aqui é o termo de conceito mesmo. Eu vou beber água posso deixar alguma coisa, viu? Viu? É verdade aqui, né no carro da água. Você já colocou completo muito bem viu? Você é uma segurança mesmo não eu só faço aqui. Enfim, o segurança tem que identificar que ele não tá falando.
Tá chovendo ela tá tudo bem bastante água também esse negócio aí, mas é que ele papo é a comida acredita mais alguém interessa um copo de água um rolinho de café. Cadê minha prima que chegou agora que eu não vi ela você deseja alguma coisa uma bolacha minha meu que eu posso nem servir agora é uma bolachinha para quem chega por último ainda tem coisa já que você tá tão cordial eu vou dizer agora tem água aqui eu não vou aceitar da sua água e terminar essa.
Mais água aqui tá gente beber água do índio, você vai voltar sempre dessa água para você estar sempre conosco, tu já veio. Eita água boa com gostinho de Fanta ainda né da garrafa vai passar o garçom ele tinha limpado uma para tu mesmo que é o suficiente Milena, Jefferson. Ainda está aqui, por gentileza tá aqui ó do lado do Mael mais algumas pessoas que vê.
Alguma pessoa quer alguma coisa doce para adoçar a boca aí fechou e aqui gente eu vou só eu tenho pressão que está faltando Milena mesmo, só eu vou só conferir mais uma vez o CPF de Cleonice tá faltando a única que tá faltando mesmo. Ela se contou me deu mas eu vou já procurando aqui que eu posso ter em alguma coisa aqui, eu vou falar com a minha irmã para ela enviar um momento a nossa segurança.
Tem nenhum documento. Mas a senhora tem que ter cuidado acontece algum acidente com você andar já tá cuidando do Sul. Ela tá com sua identidade seu CPF pronto.
Cadê tu não vai se perturbar né? Cadê os documentos nunca tinha me pede energia então não tomou suquinho. Não ontem não né? Tá de boa. Tô ligando para ela, viu? Segurança.
Além de ser da área da saúde também é para trazer eles com deficiência que só faltou Milena, pera aí Jefferson. E quando a gente tá concluindo aqui deixa a Milena se apresentar tá gravando tá gravando né, Moisés? Mas eles continua gravando né? Só fazer um silêncio para Milena se apresentar para ficar registrado.
Não tava já junto com Jaciara eu faço parte da liderança de mulheres, Ibirapuã, cunhado, faço parte do coletivo e também faço parte do coletivo, Ibirapuã Produções é o coletivo de audiovisual que a gente faz para registrar nossas memórias por meio de nós mesmos seja bem-vinda ao grupo antes de você chegar só confirmando só dizendo para você que esse grupo que tá aqui na nossa terceira rodada aqui, já vai ser para confirmação dos resultados. A gente vai tratar resultados por aldeias confirma que a gente é o que a gente chama lá pesquisa de validação dos dados a gente vai validar esses dados com vocês e por último é que a gente vai já com os dados validados cruzar um programa para poder ter os resultados finais. Tá certo? Já botei Cilene.
Ela entra como agricultora também ou só pescadora pode ser pescadores. Com certeza.
A semana da josenice conselho também amigo, tá lá nesse caderno agora liderança política Cacique Milena, mas coloca lá da produção audiovisual, tem um tracinho.
r a p o agudo gente de várias áreas de conhecimento")
contaPalavras(linhas)